"""enum Degerleri guncellendi

Revision ID: 819e4e804bb9
Revises: 45c91666d901
Create Date: 2025-08-21 02:33:30.056486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '819e4e804bb9'
down_revision = '45c91666d901'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
