"""add_rbac_system

Revision ID: dd5dcdc46b07
Revises: d8aa88dfe453
Create Date: 2025-08-20 15:41:09.648561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5dcdc46b07'
down_revision = 'd8aa88dfe453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Önce enum türlerini oluştur
    userstatus_enum = sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus')
    userstatus_enum.create(op.get_bind())
    
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.add_column('tickets', sa.Column('escalated_to_id', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('last_updated_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['last_updated_by_id'], ['id'])
    op.create_foreign_key(None, 'tickets', 'users', ['escalated_to_id'], ['id'])
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('status', userstatus_enum, nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status')
    op.drop_column('users', 'role_id')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'last_updated_by_id')
    op.drop_column('tickets', 'escalated_to_id')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    
    # Enum türünü sil
    userstatus_enum = sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='userstatus')
    userstatus_enum.drop(op.get_bind())
    # ### end Alembic commands ###
