"""Create users and tickets tables v2

Revision ID: e54b9f90a9c2
Revises: f1da83af47bc
Create Date: 2025-08-20 14:44:19.097239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e54b9f90a9c2'
down_revision = 'f1da83af47bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
