"""Create users and tickets tables v3

Revision ID: e8c3681b1280
Revises: e54b9f90a9c2
Create Date: 2025-08-20 14:45:07.546790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c3681b1280'
down_revision = 'e54b9f90a9c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
